[package]
name = "registry"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { workspace = true }

adapter = { workspace = true }
kernel = { workspace = true }

mockall = { workspace = true}
